# Generated by Django 3.0.2 on 2020-01-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
